name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/dataset_preprocessing/telco-customer-churn_preprocessing.csv"
  TARGET_VAR: "Churn"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check Env
      run: |
        echo $CSV_URL

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
        pip install python-dotenv

    - name: Run MLflow Project
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/rafifardhana1503/Membangun_model.mlflow/
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        mlflow run MLProject --env-manager=local

    - name: Get latest MLflow run_id from DagsHub
      id: get_run_id
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/rafifardhana1503/Membangun_model.mlflow/
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        python scripts/get_latest_run_id.py | tee get_run_id.log
        RUN_ID=$(grep RUN_ID get_run_id.log | cut -d'=' -f2)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        echo "Latest run_id: $RUN_ID"