name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CSV_URL: "MLProject/dataset_preprocessing/telco-customer-churn_preprocessing.csv"
  TARGET_VAR: "Churn"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check Env
      run: |
        echo $CSV_URL

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow

    - name: Run MLflow Project
      run: |
        mlflow run MLproject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        RUN_ID=$(ls -td mlruns/0/*/ | head -n 1 | cut -d'/' -f3)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"