name: CI/CD MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  EXPERIMENT_NAME: Modelling_tunning_manuallog
  CSV_URL: MLProject/dataset_preprocessing/telco-customer-churn_preprocessing.csv
  TARGET_VAR: Churn

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Check Env
      run: |
        echo $CSV_URL

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
        pip install python-dotenv

    - name: Run MLflow Project
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/rafifardhana1503/Membangun_model.mlflow/
        MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
      run: |
        mlflow run MLProject --env-manager=local

    - name: Get latest MLflow run_id
      run: |
        echo "Getting latest run ID..."
        python <<EOF
        import mlflow
        client = mlflow.tracking.MlflowClient()
        experiment = client.get_experiment_by_name("${{ env.EXPERIMENT_NAME }}")
        if experiment is None:
          raise Exception("Experiment not found.")
        runs = client.search_runs(experiment_ids=[experiment.experiment_id], order_by=["start_time DESC"])
        if not runs:
          raise Exception("No runs found in the experiment.")
        run_id = runs[0].info.run_id
        print(f"Latest run ID: {run_id}")
        with open("${GITHUB_ENV}", "a") as f:
          f.write(f"RUN_ID={run_id}\n")
        EOF